# Generated by Django 6.0.5 on 2026-08-03 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_populate_owner_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('3fe2dea5-68fc-42e5-a7d9-85b42f3b5a8f'), editable=False, unique=True),
        ),
    ]
