# Generated by Django 6.0.5 on 2026-08-03 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('391c5b35-d27a-4bc3-898e-84c707046c83'), editable=False, unique=True),
        ),
    ]
