[tool.poetry]
name = "kanban-saas"
version = "0.1.0"
description = "SaaS project management platform"
authors = ["Leonid Kalintsev <lensuperhero@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
django = "^6.0"
djangorestframework = "^3.17"
psycopg2-binary = "^2.9.12"
django-environ = "^0.13.0"
django-redis = "^6.0.0"
djangorestframework-simplejwt = "^5.5.1"
celery = {extras = ["redis"], version = "^5.6.3"}
channels = "^4.3.2"
daphne = "^4.2.3"
channels-redis = "^4.3.0"
drf-spectacular = "^0.30.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"